apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-node-deployment
  labels:
    app: hello-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-node
  template:
    metadata:
      labels:
        app: hello-node
    spec:
      containers:
      - name: hello-node
        image: 127.0.0.1:30400/hello-node:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

